import streamlit as st

from src.data_loader import load_data, clean_data
from src.recommender import recommend_products


# Load and clean data
df = clean_data(load_data())


# App title
st.title("🛒 Smart Supermarket AI")

st.write(
    "Welcome to the Smart Supermarket AI Recommendation System."
)


# Sidebar
st.sidebar.header("Recommendation Settings")

top_n = st.sidebar.slider(
    "Number of recommendations",
    min_value=1,
    max_value=5,
    value=3
)


# Generate recommendations
recommendations = recommend_products(df, top_n=top_n)


# Display results
st.subheader("🔥 Recommended Products")

st.dataframe(
    recommendations,
    width="stretch"
)


# Simple explanation
st.info(
    "Recommendations are generated by analyzing product sales "
    "and identifying the highest-selling product categories."
)